MaxEventSize = 0 # value 0 unlimit the maximum event size that can be sent to message bus or core-data

[Writable]
LogLevel = "INFO"

[Service]
Port = 59900
StartupMsg = "device virtual started"

[MessageBus]
  [MessageBus.Topics]
  PublishTopicPrefix = "edgex/events/device" # /<device-profile-name>/<device-name>/<source-name> will be added to this Publish Topic prefix
  DeviceCommandRequestTopic = "edgex/device/command/request/device-virtual/#"  # subscribing for inbound command requests
  ResponseTopicPrefix = "edgex/response" # /<service-name>/<request-id> will be added to this prefix topic
  MetadataSystemEventTopic = "edgex/system-events/core-metadata/+/+/device-virtual/#"
  [MessageBus.Optional]
  ClientId = "device-virtual"

[Device]
  ProvisionWatchersDir = ""