[Service]
Host = "edgex-device-virtual"
Port = 49990
ConnectRetries = 3
Labels = []
OpenMsg = "device virtual started"
Timeout = 5000
EnableAsyncReadings = true
AsyncBufferSize = 16

[Registry]
Type = "consul"
Host = "edgex-core-consul"
Port = 8500
CheckInterval = "10s"
FailLimit = 3
FailWaitTime = 10

[Logging]
EnableRemote = true
File = "./device-virtual.log"

[Writable]
LogLevel = 'INFO'

[Clients]
  [Clients.Data]
  Name = "edgex-core-data"
  Protocol = "http"
  Host = "edgex-core-data"
  Port = 48080
  Timeout = 5000

  [Clients.Metadata]
  Name = "edgex-core-metadata"
  Protocol = "http"
  Host = "edgex-core-metadata"
  Port = 48081
  Timeout = 5000

  [Clients.Logging]
  Name = "edgex-support-logging"
  Protocol = "http"
  Host = "edgex-support-logging"
  Port = 48061

[Device]
  DataTransform = true
  InitCmd = ""
  InitCmdArgs = ""
  MaxCmdOps = 128
  MaxCmdValueLen = 256
  RemoveCmd = ""
  RemoveCmdArgs = ""
  ProfilesDir = "./res"

# Pre-define Devices
[[DeviceList]]
  Name = "Random-Boolean-Device"
  Profile = "Random-Boolean-Device"
  Description = "Example of Device Virtual"
  Labels = [ "device-virtual-example" ]
  [DeviceList.Protocols]
    [DeviceList.Protocols.other]
      Address = "device-virtual-bool-01"
      Port = "300"
  [[DeviceList.AutoEvents]]
    Frequency = "10s"
    OnChange = false
    Resource = "Bool"
[[DeviceList]]
  Name = "Random-Integer-Device"
  Profile = "Random-Integer-Device"
  Description = "Example of Device Virtual"
  Labels = [ "device-virtual-example" ]
  [DeviceList.Protocols]
    [DeviceList.Protocols.other]
      Address = "device-virtual-int-01"
      Protocol = "300"
  [[DeviceList.AutoEvents]]
    Frequency = "15s"
    OnChange = false
    Resource = "Int8"
  [[DeviceList.AutoEvents]]
    Frequency = "15s"
    OnChange = false
    Resource = "Int16"
  [[DeviceList.AutoEvents]]
    Frequency = "15s"
    OnChange = false
    Resource = "Int32"
  [[DeviceList.AutoEvents]]
    Frequency = "15s"
    OnChange = false
    Resource = "Int64"
[[DeviceList]]
  Name = "Random-UnsignedInteger-Device"
  Profile = "Random-UnsignedInteger-Device"
  Description = "Example of Device Virtual"
  Labels = [ "device-virtual-example" ]
  [DeviceList.Protocols]
    [DeviceList.Protocols.other]
      Address = "device-virtual-uint-01"
      Protocol = "300"
  [[DeviceList.AutoEvents]]
    Frequency = "20s"
    OnChange = false
    Resource = "Uint8"
  [[DeviceList.AutoEvents]]
    Frequency = "20s"
    OnChange = false
    Resource = "Uint16"
  [[DeviceList.AutoEvents]]
    Frequency = "20s"
    OnChange = false
    Resource = "Uint32"
  [[DeviceList.AutoEvents]]
    Frequency = "20s"
    OnChange = false
    Resource = "Uint64"
[[DeviceList]]
  Name = "Random-Float-Device"
  Profile = "Random-Float-Device"
  Description = "Example of Device Virtual"
  Labels = [ "device-virtual-example" ]
  [DeviceList.Protocols]
    [DeviceList.Protocols.other]
      Address = "device-virtual-float-01"
      Protocol = "300"
  [[DeviceList.AutoEvents]]
    Frequency = "30s"
    OnChange = false
    Resource = "Float32"
  [[DeviceList.AutoEvents]]
    Frequency = "30s"
    OnChange = false
    Resource = "Float64"
